{% set version = "2.2.2" %}

package:
  name: python-hdfs
  version: {{ version }}

source:
  fn: hdfs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/hdfs/hdfs-{{ version }}.tar.gz
  sha256: df8c99e359d7351c7ef70efaceea8238f8311035701c235a57ba98fbac26c932

build:
  number: 0
  entry_points:
    - hdfscli = hdfs.__main__:main
    - hdfscli-avro = hdfs.ext.avro.__main__:main
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - docopt
    - fastavro >=0.9.6
    - pandas >=0.14.1
    - requests >=2.7.0
    - requests-kerberos >=0.7.0
    - six >=1.9.0

test:
  imports:
    - hdfs
    - hdfs.ext
    - hdfs.ext.avro
    - hdfs.ext.dataframe
    - hdfs.ext.kerberos

  commands:
    - hdfscli --help
    - hdfscli-avro --help

about:
  home: http://hdfscli.readthedocs.org
  license: MIT
  summary: 'HdfsCLI: API and command line interface for HDFS.'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
    - parente
