travis:
  secure:
    BINSTAR_TOKEN: kwzVV0ml+cNezhj0lKVVgLG0IqAqTRZEKd4e0TSOdnVsyCD1XTKTBR0Z6dixNd7LYGE1bVaP0/bE7Wteo4WQue+kloH87OjcrrpuzdkVF3SSfx8OSHP6Dvt2MpkOd6epykd6NyVUUemZ84OOez+3H74KNz7g7FA7sDthUAMNWYoVvagKpFr1LC21QfPVJgo/9qE1WHy+gGEI6SNr1jUM+PLHB6r0+hBChhyo9oqfOBFcm4e/cM/1Pnsc+cw86+7BwJMmTV0sdsIG/A7a0vM9Mrxb5tc0fhkpitO4fpcwNhBAjtOEoTcEodfvzvDOHTs8gRfdqHWkIFOIwUAINbSAMx+E4tSPUw8GXf/GoVSfse6yfWxf4WFrHlhS6R9it7wUq4UO1biVAvnc1x6B7qDkFPcZ6urlmjjdSZPNAERCA/WKSp/CVIx4gUhOJqDrfzlRYZ+OyXWGlXPGj5BF5YcG0LE/K1wM2gxAed/r18gv2ZkLfF/DiYh/wGS4E/jIQ82cRL7ok9h2pVI8+9NewfhpMyPOkMS7mg53xlLE+m5ZXyWmIzjuDZsj3uruElkPSwJzRgQphv2i9Cosy7VyZqMwmhrrbpGkefsA6PSPFBjl5NdLDL0iH1CgvDgX6ujkBS/5MDvy8SLhajEGqUfybNgVDJfUinklFIGabCcbwTiQBVs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
