travis:
  secure:
    BINSTAR_TOKEN: l0GhsSarqZ+fGhLv2bTvLeVAP/aXpwDZge2mDclhVNSpl4+ZiAkKpwx5kgC46e+UkkhyiyPb5eaDwXx7L5nxb90Xl3ni0Q1YZSTUtDQ5zeBqHZMU4Mm8pmOybz2hhz+n2atbUZ2P1IsBuxtmnUD60sjhqr2hPnp92YE5AMn3olkSAaNbgUEzkd61xjBX4QC7e+qr03h5kuT6UrJR7XKoF1krhdkuxLa7bveGsH1+AVa9UGWMm5OrnzKAHNc8MiygZN0cGa2GuKTqcJ3qgAJL0tRVD0JsDlrdCuMfl5snfGhGBi6pyLbxZQ8vbw8VAycW6E/sE0Ux1kHiOzy3hZaHX9UVziQEZAqtR7SsRmdDmnSEQweN2NVtFs4MQVjR18bqDr1+U/kBqlqZvffj8bJxNQHwj009Wj84kOnhjSMJ7IZKgpA0w2LuNZ4ELfqvWFNjs1A4vDekgOuBQ4jDCRg1iXA4LG8JP4GcMl6ciUzn8UgEqvXP1Uzg/N/hwoMFDJQkk5OXKaplUc+ZaOQqD2eeP2W+MsqyyK4sAUpRTop5ga89iMK7bFpg6i571dUJ7fhmAnsORcyXVSlIPRSV/nqs86k/bJWu1XjI8msz+JZit3MuJ//0A6hl7nJgvYoBsI6Fz1jBFcjlbZ9PVydn2PkYewcWHGT7+OnrnR+2Y9vxOK8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
