travis:
  secure:
    BINSTAR_TOKEN: ZzmiUI+v8DJOM0AK3c+hblunahNgkIhMLTgAOxIQA0o8usrd9i74xdg976BORGYQVnWHnnm1JlUu/uiyj0AT1+WF233dEo1hOVEqYX3XGslAhyCYvvUNkpDU4APwLK/KDzQFBPP6grlDpzIS8RNIawBp02hwUvOHy5sZEQxpSSFhaFXEfZw2xYpH5PMGueaRBI9pUzzLGV3jIlAcQbp1W4Iriiuh6SX1HyG175IAGUmN8V0lwANSFL1IOncm5jIFTc18wWcHJpN4N/UAt+Q11ZrK2Rpjy+KhW3Zx0oAz+AitqDKdhW48yGeay4uNBzRHDzi2M0zXobb6Tv7SvcbTkOLjq1z0pguBSbwVUgIL1m81qHAluDcDh8NOnRM1i783awbCOefeE04shExz4TIoUHLuQNaBlm2GQa8CWdtqz+iW9BWryaiyrvh7kg5NfeP4CgtAmAU5kjOb7ozSWD20bwcl/yU4Gt5ptkyJT2Kugq3gP+P5iH1nhNWIwfwqSViIeVx9QJz6QQ2twD8uMa6fPlc0/lFnM/Fu4Ch/UqLkPSWmEX3MDYdWaBfyRE+3oFvCgmRXJWnyj8mO5lJzIcaEMk0RZ0H192LjaRU32z6sRjCMb0Z3iuc/7H206rqf3D2mnU6H7eqV0Z9/vz4X5U5Jg832vmbci1Wk1Z8lHOm8MH8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
