travis:
  secure:
    BINSTAR_TOKEN: ZF52whlPcBYceM84Spz3I0BVQLrpqtECcVIVA6t/u89ijigMxCLQ/FX4ieFw0zPRfXE84XP2Am/9V6tM3fB5z+EKMnnWNqdAHaFk5gnd+xMASJWXuBT8SkPeGwHN5uiZlQysCvGVFN+mHx3A+7okokBhM6+DPMeo4r0wtGH9z19/tXfGeMBKJivTbvpxwMzFql71e78nEeOO29PxvIUmVHBJBFcl2NrLUIVUf+j1Qz49YwFojz061hNuX2SUiEPeJSWJ5nGa1FBz3JIlmCZbhwmbqYXZBJuIVTmCz1rCudh21D6RXjqiL9+GK5arqDanSDk2gcx7bOBanGxxO51RouhST85i7RaHDRfLW5FtHYt3c1rz06RcsoDFbAZkJYTXmWJiJBIKBnzFL8K5clY1eyYyFUuO2IjpQ2LcuE1e/1ICmGlmnpJzerCKbQ8ANMgn9K5JHsK6Ejrk3Kdx5e4X0gqvQ/RpJTgOcpNivAbavLNU6135AW5+vmSmNnLIL5RZSs4kZfTBDZhUHk2nzrRDHbOH96Z7wJOPEzf9NMmUmTIXZcELzckYUshoCGvkmTHRBPuCFBfk1UU+p0X6esQ9IA5DAFDCfXstdW+u8H4VFfraeYQ1XXKBjAE2b4nHcoU7H7lusMhd3QX+P3FWMdsZKPQvQc3ZerEi3KrLRveIK/E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
